services:
  app:
    image: 'jopka:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jopka
      - SPRING_DATASOURCE_USERNAME=jopka
      - SPRING_DATASOURCE_PASSWORD=jopka
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=jopka
      - POSTGRES_PASSWORD=jopka