services:
  app:
    image: 'sullssul/jopka:latest'
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jopka
      - SPRING_DATASOURCE_USERNAME=jopka
      - SPRING_DATASOURCE_PASSWORD=jopka
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_USER=jopka
      - POSTGRES_PASSWORD=jopka
    volumes:
      - "jopka_data:/var/lib/postgresql/data"
      -
    pgadmin:
      container_name: pgadmin_container
      image: dpage/pgadmin4:5.7
      environment:
        PGADMIN_DEFAULT_EMAIL: "jopka"
        PGADMIN_DEFAULT_PASSWORD: "jopka"
        PGADMIN_CONFIG_SERVER_MODE: "False"
      volumes:
        - ./pgadmin:/var/lib/pgadmin
      ports:
        - "5050:80"
      restart: unless-stopped
      deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: 1G
volumes:
  jopka_data:
    driver: local