name: JIB container publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: JIB container build and publish
        uses: sullssul/jopka
        with:
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
